name: Sync All Historical Releases
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Releases
        uses: itsmeyg/sync-releases-action@v1
        with:
          source_repo: "Wangnov/codex-app-mirror"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
